INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MADDR1, MADDR2, MCONSENT)
    VALUES ('ADMIN', 'ADMIN', '관리자', 'a@a.com', '서울시', '아파트', 7);

INSERT INTO CATEGORY VALUES (10, '노트/다이어리', 0, NULL);
INSERT INTO CATEGORY VALUES (20, '문구', 0, NULL);
INSERT INTO CATEGORY VALUES (30, '취미', 0, NULL);
INSERT INTO CATEGORY VALUES (40, '키친/홈데코', 0, NULL);
INSERT INTO CATEGORY VALUES (50, '패브릭/생활', 0, NULL);

INSERT INTO CATEGORY VALUES (11, '노트', 1, 10);
INSERT INTO CATEGORY VALUES (12, '단어장/수첩', 1, 10);
INSERT INTO CATEGORY VALUES (13, '메모지', 1, 10);
INSERT INTO CATEGORY VALUES (14, '다이어리', 1, 10);
INSERT INTO CATEGORY VALUES (15, '스케줄러/플래너', 1, 10);

INSERT INTO CATEGORY VALUES (21, '필기구', 1, 20);
INSERT INTO CATEGORY VALUES (22, '필통', 1, 20);
INSERT INTO CATEGORY VALUES (23, '스티커', 1, 20);
INSERT INTO CATEGORY VALUES (24, '마스킹테이프', 1, 20);
INSERT INTO CATEGORY VALUES (25, '파일', 1, 20);
INSERT INTO CATEGORY VALUES (26, '사무용품', 1, 20);
INSERT INTO CATEGORY VALUES (27, '데스크소품', 1, 20);
INSERT INTO CATEGORY VALUES (28, '카드/편지지', 1, 20);

INSERT INTO CATEGORY VALUES (31, 'FUN/TOY', 1, 30);
INSERT INTO CATEGORY VALUES (32, 'DIY 취미', 1, 30);
INSERT INTO CATEGORY VALUES (33, 'PARTY', 1, 30);
INSERT INTO CATEGORY VALUES (34, '피규어', 1, 30);

INSERT INTO CATEGORY VALUES (41, '키친용품', 1, 40);
INSERT INTO CATEGORY VALUES (42, '텀블러', 1, 40);
INSERT INTO CATEGORY VALUES (43, '머그/컵', 1, 40);
INSERT INTO CATEGORY VALUES (44, '시계', 1, 40);
INSERT INTO CATEGORY VALUES (45, '조명', 1, 40);
INSERT INTO CATEGORY VALUES (46, '디퓨저/방향제', 1, 40);
INSERT INTO CATEGORY VALUES (47, '인테리어소품', 1, 40);

INSERT INTO CATEGORY VALUES (51, '담요/방석', 1, 50);
INSERT INTO CATEGORY VALUES (52, '욕실용품', 1, 50);
INSERT INTO CATEGORY VALUES (53, '청소/정리용품', 1, 50);
INSERT INTO CATEGORY VALUES (54, '칫솔 케이스/살균기', 1, 50);

COMMIT;
----------------------------------------------------------------------------------------------------------------
-- 테스트용
DESC MEMBER;
DESC CATEGORY;
DESC PRODUCT;
DESC PRODUCT_WISH;
DESC REVIEW;
DESC REVIEW_IMAGE;
DESC REVIEW_LIKE;

SELECT * FROM PRODUCT;
select * from product where cid='54';
delete from product where cid='54';
delete from product;
SELECT * FROM MEMBER;
SELECT * FROM CATEGORY order by cid asc;

INSERT INTO MEMBER VALUES ('CKSUN', 'CKSUN', '최경선', 'b@b.com', '서울시', '아파트', 0, 1997, 03, 28, 7, SYSDATE);

INSERT INTO PRODUCT VALUES ('A12345678901', 11, '&', '&', '&', 1000, '하나(외환)카드 결제 시 최대 8개월 무이자', '2,500원 (30,000원 이상 무료배송)', '&');

INSERT INTO REVIEW VALUES ((SELECT NVL(MAX(RNO),0)+1 FROM REVIEW), 'A12345678901', 'CKSUN', 'CONTENT', SYSDATE);

-- 후기 목록 보기
SELECT * FROM REVIEW 
    WHERE PID='A12345678901'
    ORDER BY RNO DESC;












